### ISSUE TITLE
[Proposal] Implement Tests and Travis CI Integration

### ISSUE THREAD

**Issue by clsource** [wireshell/wireshell#18]
Implementing tests and integrating with Travis CI

http://www.phptherightway.com/#testing
https://travis-ci.org/

Will make the app more robust and mature :+1:

**Comment by marcus-herrmann** [comment]
Absolutely, was toying with the idea for the same reason. But got stuck at the part where wireshell meets the ProcessWire API. Not yet sure how to fake that in a test context.

**Comment by clsource** [comment]
The test suit could be a pre filled processwire install (site profile?). That haves all the data needed for doing what wireshell needs to do :pig_nose: . So for testing first you need a test ready PW site. :smile:

**Comment by marcus-herrmann** [comment]
Sure, but that test install itself needs a database initiated on every test run, basically a virtual machine. I'm not that experienced in testing to instantaneously how to approach that. :)

**Comment by clsource** [comment]
I think first you have to execute a command like

`wireshell test:preprare`

that creates a PW install with a test site profile

then

`wireshell test:begin`

to execute all tests with a single PW install, not needing a new install on every test.

**Comment by marcus-herrmann** [comment]
By test run I meant e.g. a Travis run. You're referring to the same I guess?

Aside from how often such a scenario would be created or destroyed I'm not sure how to create it in the first place (Vagrant box?) for e.g. Travis to catch the tests, setting all dependencies (PW in this case) up, run the tests, and report back.

**Comment by clsource** [comment]
I will read some more about Travis and look a way to integrate it with PW. :+1:

**Comment by clsource** [comment]
So far I have been reading about PHPUnit.
But BDD (Behaviour Driven Development) is a very cool way of testing.

http://www.slideshare.net/marcello.duarte/full-stack-bdd-for-symfony2
http://everzet.com/post/31581124270/fullstack-bdd-2012-wrapup

**Comment by marcus-herrmann** [comment]
Absolutely fascinating topic. I learned a bunch about testing and BDD/TDD from @jeffreyway and laracasts.com and finished just today my first Laravel customer project, with full tests, of course. :)

**Comment by clsource** [comment]
May be we can do like PW and create a checklist for things to test and expected outcome. that way we could test :).

also I found this https://styleci.io/ that enables to check the php code on merge :+1:

**Comment by marcus-herrmann** [comment]
Good ideas, both issues. Maybe it just comes down to mock the `wire();` function?
