### ISSUE TITLE
[Question] is wireshell.pw editable?

### ISSUE THREAD

**Issue by clsource** [wireshell/wireshell#23]
I wonder if the main site and documentation for wireshell are editable.
maybe a new repo dedicated only to documentation could be the way to go.

here's an example for docs.

https://github.com/ParsePlatform/Docs

and a static site generator could be used as well 

example:

http://gohugo.io/

:+1:

**Comment by marcus-herrmann** [comment]
Thanks for the idea. Will revamp wireshell.pw some time in the future, and possibly make it based on ProcessWire (ironically it isn't yet, but a boring static site), and then maybe use a fork of @owzim Recipe Installer to enable markdown-based contributions to the docs.

**Comment by clsource** [comment]
I have an idea.
A repo could be made and edited in markdown. when a commit is made in master, a hook triggers and generates the new documentation site.

Also maybe a cron job could fetch the lastest changes from the doc repo and updates the site if needed.

Or use github pages

https://pages.github.com/

If wireshell will have multiple repos a proper namespace in github could become handy.

ex:
 github.com/wireshell/wireshell
 github.com/wireshell/docs

:+1:

**Comment by marcus-herrmann** [comment]
Nice! I'm sure we'll get back to these ideas in the future :+1:

**Comment by justonestep** [comment]
* edit [wireshell.pw](https://github.com/wireshell/wireshell.github.io)
* edit [docs.wireshell.pw](https://github.com/wireshell/wireshell)

😀
