### ISSUE TITLE
Site color 

### ISSUE THREAD

**Issue by harikt** [wireshell/wireshell#24]
Hey @marcus-herrmann and team,

Good work on making a website :+1:  and adding new features.

I have one suggestion, I don't know how you feel it. I like white color background than dark. It helps to read the contents. Are you guys ok to change the site background from dark one to a light one ?

Thank you.

**Comment by marcus-herrmann** [comment]
Thanks for the feedback on this! As mentioned in #23 wireshell.pw will change in the future (no precise agenda on this, though) and maybe a style switcher (dark mode/bright mode) is a good idea for this issue.

**Comment by justonestep** [comment]
The background color has changed, see [docs](http://docs.wireshell.pw/). 🙂

**Comment by harikt** [comment]
thank you :) .
