### ISSUE TITLE
Ability to specify version of processwire

### ISSUE THREAD

**Issue by hagcin** [wireshell/wireshell#30]
Would be nice to specify a version of a version of processwire and not just use the latest stable.

**Comment by justonestep** [comment]
I assume you're talking about the **New Command**? You can choose whether to install the latest dev or stable version (master or dev branch). Add ```--dev``` to get the latest dev version. This should be enough, it's not recommended to install an older version. Run ```$ wireshell new --help``` to get more informations.

**Comment by hagcin** [comment]
I notice wireshell gives the ability to specify commits for modules...doing
it for provesswire could be helpful as well.

Use case: multiple test environments that are created and destroyed at all
different times. When created they should not be running a different
version from production, or it can add a level uncertainty best avoided.
Once the latest stable is tested and determined safe with all installed
third party modules  one would just need to change the commit or version
number called by wireshell.  I notice Ryan states in the commit history of
the Dev branch when he merges to master and leaves version information in
the commit so the dev branch could work great as well if one could specify
a commit...just a feature to consider.

**Comment by justonestep** [comment]
Depending on the new `devns` branch (dev with namespace support) I added some litte improvements for the **New** and **Upgrade** command (both in the same way).

There are four ways to specify the version / branch:

1. **-** : no param to get master / current stable branch

        ❯ wireshell new projectname
        ❯ wireshell upgrade

2. **--dev** : to get dev branch

        ❯ wireshell new projectname --dev
        ❯ wireshell upgrade --dev

3. **--devns** : to get devns branch

        ❯ wireshell new projectname --devns
        ❯ wireshell upgrade --devns

4. **--sha=xxx** : to get a specific commit / version

        ❯ wireshell new projectname --sha=cffb682836517065d7dd7acf187545a4a80f1769
        ❯ wireshell upgrade --sha=cffb682836517065d7dd7acf187545a4a80f1769

**Comment by hagcin** [comment]
very cool!

On Fri, Oct 23, 2015 at 9:45 AM, Bea Dav <notifications@github.com> wrote:

> Closed #30 <https://github.com/wireshell/wireshell/issues/30>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wireshell/wireshell/issues/30#event-443819202>.
>



-- 
Nicko Winner
Professional Web Designer
*NickoCreations.com*
860.377.6642
