### ISSUE TITLE
[Proposal] Use the same PHP version supported in PW to develop wireshell

### ISSUE THREAD

**Issue by clsource** [wireshell/wireshell#33]
I think that wireshell should be developed under the same version as supported by Processwire. In that way wireshell will work under the same server configurations. at least test wireshell with the minimal requirements that pw need.

:+1:

**Comment by marcus-herrmann** [comment]
I see your point, but consider two things:

a) I see ws primarily as a command line helper for local development of sites and only secondarily as a tool to be executed on production environments. I assume a user utilizing wireshell or any other command line app is aware of PHP versions and that 5.3 was EOLed more than a year ago. Besides: you have to have SSH access to that mentioned hypothetical production server. I find it most unlikely that a PHP version released 4 years ago would be the only PHP version available on said server.
b) ws itself is a companion app to PW, but not a module and based on another framework (Symfony).

But in the end it could be a majority vote amongst us core maintainers. At least for me, investing work to cater vintage PHP versions would feel like a step backwards.

**Comment by clsource** [comment]
yes you are right. I agree with your opinion.

At least we could detail on wich versions of php wireshell should be tested.
5.4, 5.5?

:+1:

**Comment by justonestep** [comment]
.. and 5.6 😀

**Comment by cstevensjr** [comment]
Just an outsider, however PHP 5.4 is soon slated for EOL.

**Comment by clsource** [comment]
I should upgrade my servers then haha :100:

**Comment by clsource** [comment]
this should be closed i think.
