### ISSUE TITLE
The Command autoload approach, core and module-based

### ISSUE THREAD

**Issue by marcus-herrmann** [wireshell/wireshell#34]
See https://github.com/wireshell/wireshell/blob/feature/autoload/app/wireshell.php#L110 - core Command loading works fine with this, but I can't (literally) grasp potential Command files within /site/modules dir, also regarding their namespace and how to introduce them to the composer autoloader/psr-4. Any ideas @clsource @justonestep ?

**Comment by clsource** [comment]
I propose creating a module for PW with hookable methods and an admin page. Then you enable/disable custom commands. That creates a json file that wireshell could use for autoloading. The module checks for possible conflicts.

**Comment by clsource** [comment]
I found a simple config syntax called neon
https://github.com/nette/neon
http://ne-on.org/

**Comment by clsource** [comment]
I suggest that wireshell 0.5.1 have the autoloading of core commands. Then the next version we could play with adding custom commands. As I think version 1.0 must have custom commands enabled.

:smile:

**Comment by marcus-herrmann** [comment]
Module as bridge between PW and WS sounds good, worth a try!

As autoloading of core files does not contain any advantage for normal users (it's just an internal milestone) I would prefer to release @justonestep 's great updates in #30 as 0.5.1 and keep the whole autoloading issue with 1.0.0 - and maybe it's possible to have proper test coverage. Right now, releasing half the autoloading (the boring part :D) would be hasty.

**Comment by marcus-herrmann** [comment]
Just thinking out loud here... That "bridge file", telling wireshell where to find module-provided commands and how to autoload them - can't this be the ProcessWire 3's own composer.json? Or is that idea too narrow minded because it would require PW-module installation exclusively via composer to work?

Also, thoughts on idea: Making wireshell 1.0.0 PW 3-only, embracing its composer-goodness?

**Comment by marcus-herrmann** [comment]
Additional (loud) thought: If glueing WS1 to PW3, maybe let's change wireshell in two projects:

* wireshell bootstrapper: *Globally* installed, dealing with the heavy lifting (downloading, installing, grunt work stuff)
* wireshell: Installed locally in per-PW3-installation-composer.json. No "multiple classmaps" hassle. If wireshell is installed in this PW installation, and its modules "emitt" Commands, they will be available in `$ wireshell`.

Why am I proposing this? ;) Even with @clsource idea of an intermediary file (see above) I heavily fail to find a solution to load "local"/"installation" modules.

**Comment by clsource** [comment]
I think its a good idea in making 2 versions of wireshell
one for PW 2.x  and other por PW 3.x

the current version will work for 2.x but will not have all the 3.x goodies like custom commands via modules and that stuff.

So I propose
keep wireshell as is for 2.x 
and work a new wireshell for 3.x using all the new awesome tools that PW brings on :)
