### ISSUE TITLE
Feature to import page content (body)?

### ISSUE THREAD

**Issue by samuell** [wireshell/wireshell#37]
Is it currently possible to import page content for a specific page/field?

If not, are there plans for this?

I guess it would make most sense to pipe larger chunks, such as body content:

```bash
wireshell page:import-field --title=SomeTitle --field=body --readfrom=stdin < body.txt
```
?

**Comment by samuell** [comment]
Yeah, as you see, I sketched on something for this in a pull request (though not really production ready code).

I figured the really easiest solution was just to take contents as a json string on the commandline.

Maybe could be improved with options from reading from specified file paths etc, when content is too big for the commandline...

**Comment by samuell** [comment]
I realized more changes I'd like to suggest. Will hack on some changes during a big drupal->processwire migration i'm working on, and will come back with a PR after I have got this into a smooth process.

**Comment by justonestep** [comment]
see [pull #40](https://github.com/wireshell/wireshell/pull/40)
