### ISSUE TITLE
Choose site profile on install

### ISSUE THREAD

**Issue by LostKobrakai** [wireshell/wireshell#41]
It would be nice to let the user choose the site profile, which should be installed.

**Comment by marcus-herrmann** [comment]
This is possible with the profile flag

```
--profile : Default site profile: `path/to/profile.zip` OR one of `beginner, blank, classic, default, languages`
```

**Comment by LostKobrakai** [comment]
Is there a reason why this is not part of the setup steps, like setting the db credentials and so on?

**Comment by justonestep** [comment]
The `--profile` option is not required and therefore it isn't part of the setup process. The standard profile is  **default**.

**Comment by LostKobrakai** [comment]
Fair enough.
