### ISSUE TITLE
Allow installation in current folder

### ISSUE THREAD

**Issue by LostKobrakai** [wireshell/wireshell#43]
It would be nice to allow for something like `wireshell new .`, which will install into the current directory. In my workflow there's almost never a situation, where I want tools to install anything into subdirectories.

**Comment by justonestep** [comment]
You can't imagine how often I had to delete the just created folder before using this command. The `directory` argument is now optional, so if you want to install into the current directory, just skip it.

Little note: After downloading/installing the `ls` command won't display anything. You have to refresh the current directory (cd ., cd $PWD, cd `pwd`, ..).
