### ISSUE TITLE
Feature request: support for pre-downloaded PW zip

### ISSUE THREAD

**Issue by hanthethanh** [wireshell/wireshell#47]
It would be helpful to support  the option to install PW from a pre-downloaded PW zip, instead of downloading it. Similar to `--profile`, but for PW.

**Comment by justb3a** [comment]
Let me introduce the option `--src=path/to/source`; **src**: Path to pre-downloaded folder, zip or tgz.

If the target directory already includes an extracted source, it will use it by default.
