### ISSUE TITLE
Seems to fail installing from composer

### ISSUE THREAD

**Issue by quesada** [wireshell/wireshell#48]
I'm new to php so this may well be a silly user error:

 /v/w/h/c/site> composer global require wireshell/wireshell
Changed current directory to /home/vagrant/.config/composer
The "https://packagist.org/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Name or service not known
failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date

  [Composer\Downloader\TransportException]
  The  "http://packagist.org/p/wireshell/wireshell%24402dca7016ea0ee04d7979592dd2ac0520c85549ad09fa10a264d8377fbafb7e.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Name or service not known
  failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

**Comment by marcus-herrmann** [comment]
In this case composer could not reach packagist.org (the index of composer modules). Either packagist was down in the moment you tried to install wireshell or this was a hickup in your internet connection (or you are in an environment that prevents you from accessing packagist).

**Comment by quesada** [comment]
Thanks, that was it!
