### ISSUE TITLE
Call to undefined function Wireshell\Helpers\wire()

### ISSUE THREAD

**Issue by quesada** [wireshell/wireshell#49]
$ wireshell template:list

Error:  Call to undefined function Wireshell\Helpers\wire() (line 69 of /home/vagrant/.config/composer/vendor/wireshell/wireshell/src/Helpers/PwConnector.php)

This error message was shown because: you are using the command line API Error has been logged.

I'm sure this is some silly error on my part; but what is the problem here?
Thanks!

**Comment by marcus-herrmann** [comment]
wireshell master isn't ready yet for PW 3.0, please use our 3.0-compatible feature branch https://github.com/wireshell/wireshell/tree/feature/devns until then

**Comment by justb3a** [comment]
wireshell master is now ready for PW 3.0 👍
