### ISSUE TITLE
[Proposal] Generators

### ISSUE THREAD

**Issue by mikerockett** [wireshell/wireshell#5]
I think it would be great if we could use generators for different things, like creating module blueprints:

```
$ wireshell module:generate ProcessMyModule
$ wireshell module:generate ProcessMyModule --configurable
$ wireshell module:generate ProcessMyModule --configurable --author="author-name"
etc...
```

Would probably be best to use `generate` when creating things that are code-based. `create` should remain as-is for templates etc...

Essentially, this would create the module file, info.json file, and config file (if applicable), pre-filled with the data supplied.

**Comment by marcus-herrmann** [comment]
Will look into this Module Generator script soon, could be the base for a module:generate command: https://processwire.com/talk/topic/9671-processwire-module-generator/#entry93023

**Comment by mike-anthony** [comment]
:+1:

Yeah, bumped into that thread earlier and saw your question.

**Comment by justonestep** [comment]
see [$wireshell module:generate](http://docs.wireshell.pw/en/latest/commands/module/#generate)
