### ISSUE TITLE
Wireshell fails to extract ZIP files (for --profile, --src) on macOS Sierra

### ISSUE THREAD

**Issue by eelke** [wireshell/wireshell#50]
(Note: I first wrote this as a post on the [ProcessWire forum](https://processwire.com/talk/topic/9494-wireshell-an-extendable-processwire-command-line-interface/?do=findComment&comment=129605) 4 days ago)

---

While testing the 1.0.0 version on macOS Sierra 10.12, I ran into an issue with creating a new project using a zipped site profile: It seems Wireshell fails at extracting the profile zip due to incorrect permissions? (I did not use any older version before so I do not know if this is a new problem).  

I have exported a site profile using Ryans Site Profile Export module, and have confirmed this works on a new PW 3.0.35 project: when I set it up manually (downloading & unpacking the PW zip, unpacking my profile zip into the folder and going through manual installation of the project) everything works fine. 

Also I can create new projects using the built-in profiles correctly (ie. `wireshell new projectname --profile=blank` etc).  To be sure I even checked if I could sudo run the script but to no avail (bad idea anyway). 

Below is the (truncated) result:

    weps:Server eelke$ wireshell new thijmentest2 --verbose --profile=ProjectGenerator/site-ember-pw-profile.zip

     Downloading ProcessWire...
       10.21 MB/10.21 MB ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100%
     
     Preparing project...
    
     Extracting profile...

    [2016-10-03 08:39:59] name.ERROR: Error: Directory /Users/eelke/Documents/Werk/Server/thijmentest2/site/assets/ must be writable. Please adjust the permissions before continuing. [] []
    [2016-10-03 08:39:59] name.ERROR: Error: File /Users/eelke/Documents/Werk/Server/thijmentest2/site/config.php must be writable. Please adjust the permissions before continuing. [] []
    [2016-10-03 08:39:59] name.ERROR: One or more errors were found above. We recommend you correct these issues before proceeding or contact ProcessWire support if you have questions or think the error is incorrect. But if you want to proceed anyway, click Continue below. [] []
    
    (.. Wireshell project settings ..) 

    [2016-10-03 08:40:51] name.ERROR: Please fix the error to further proceed [] []

    Congratulations, ProcessWire has been successfully installed.
    weps:Server eelke$

As a result, the entire installation fails. After running the script, the database is empty and this is the folder structure:

![image](https://cloud.githubusercontent.com/assets/738902/19149259/3ee95c46-8bc1-11e6-943f-c13c51c13d1b.png)

Any ideas?

**Edit:** Definitely a problem with unzipping files. Very simple command:

![image](https://cloud.githubusercontent.com/assets/738902/19149270/50e8c6de-8bc1-11e6-8d8f-b2142d4ecca6.png)

It seems to be macOS Sierra related, accidentally I ran into a same kind of problem this morning doing some Homebrew tasks.
(https://github.com/caskroom/homebrew-cask/pull/22002) 

The signature of Zip files has changed apparently. 
Running 'file -Izb -- ~/Server/ProjectGenerator/processwire-master.zip' on OS X 10.11 yields:

    application/x-empty compressed-encoding=application/zip; charset=binary; charset=binary
But on macOS 10.12 all you get is:

    application/zip; charset=binary

**Comment by justb3a** [comment]
This has nothing to do with the signature of the zip file. The zip file has not the right permissions to be extracted. Please change the owner (user) of the zip file.

works for me:
`-r-x------  1 username staff  11M Oct  6 12:39 pw.zip`

leads to the error message *ProcessWire can't be installed because...*:
`-r-x------  1 100 staff  11M Oct  6 12:39 pw.zip`

**Comment by eelke** [comment]
Hi Bea, thank you for your reply.
 
With username you don't  literally mean the string 'username', right? Because my user 'eelke' is already the owner of these files. 

    $ ls -l *.zip
    -rw-r--r--  1 eelke  staff  10768604  4 okt 13:36 processwire-master.zip
    -rw-r--r--@ 1 eelke  staff   5607832  6 okt 14:10 site-ember-pw.zip

Both of these fail. Using a fresh pw-master download, and the exported profile. 

I did try your suggestion however, and changed the permissions of the processwire-master.zip file to exactly match yours. 

    $ chmod 500 processwire-master.zip
    $ ls -l processwire-master.zip
    -r-x------  1 eelke  staff  10768604  4 okt 13:36 processwire-master.zip

This yields the same result as before: 

    $ wireshell new chmodtest --src ProjectGenerator/processwire-master.zip

    Preparing project...

     ProcessWire can't be installed because the downloaded package is corrupted                          
      or because the installer doesn't have enough permissions to uncompress and                                    
      rename the package contents.                                                                                  
      **To solve this issue, check the permissions of the /Users/eelke/Documents/Werk/Server/chmodtest directory and  
      try installing ProcessWire again.**                                                                             
      wireshell new chmodtest 3.0.35        

The bold part indicates there should have been a directory created under that name. However, there is none. I have even tried with setting the permissions of the to 777, but to no avail.

**Comment by justb3a** [comment]
Did you try running the command with `sudo`? If I change the owner to something like `100` I'm not able to run the command, but when I prepend `sudo` it's working. This shouldn't be the solution, just to figure out what's going on. 

Could you please check the current working directory permissions as well? If I set the owner of the cwd to 100 the same error occurs.

**Comment by eelke** [comment]
Hi, I did run it with `sudo` too, yes. That didn't help sadly. 
I also realized that I was working in a directory with a symlink (`~/Server` is actually `/Users/eelke/Documents/Werk/Server`, but running from that (full) path did not change anything :( 

The directory's info: `drwxrwxr-x@  92 eelke  staff  3128  6 okt 12:55 Server`
I have tried with creating a new project in another (non symlink) directory inside ~/Documents, but it had the same result. I have also verified that `eelke` is the owner of both `composer` and `wireshell` (`which wireshell` and then `ls -l` the result). 

This is the full trace when running the command with `-vvv` by the way (though you probably already knew where the message came from)

```
Exception trace:
 () at /Users/eelke/.composer/vendor/wireshell/wireshell/src/Commands/Common/NewCommand.php:489
 Wireshell\Commands\Common\NewCommand->extract() at /Users/eelke/.composer/vendor/wireshell/wireshell/src/Commands/Common/NewCommand.php:122
 Wireshell\Commands\Common\NewCommand->execute() at /Users/eelke/.composer/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /Users/eelke/.composer/vendor/symfony/console/Application.php:847
 Symfony\Component\Console\Application->doRunCommand() at /Users/eelke/.composer/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at /Users/eelke/.composer/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at /Users/eelke/.composer/vendor/wireshell/wireshell/app/wireshell.php:85
 require() at /Users/eelke/.composer/vendor/wireshell/wireshell/wireshell:5
```

**Comment by justb3a** [comment]
> Are you also on 10.12?
yes

Sorry, I've no other idea :(

**Comment by eelke** [comment]
@justb3a I took a good look at Wireshells [NewCommand.php](https://github.com/wireshell/wireshell/blob/master/src/Commands/Common/NewCommand.php) file and I think I found the problem with the profiles. On line [670](https://github.com/wireshell/wireshell/blob/master/src/Commands/Common/NewCommand.php#L670) it reads `   $this->fs->mirror($extractPath, $this->projectDir . '/');`

This actually moves the profile directories and files into the root of the project, and not into the /site folder! Changing the line to `$this->fs->mirror($extractPath, $this->projectDir . '/site');` fixed that! 

In regards to the --src zip problem, I just downloaded the current PW master from github using Curl 
(`curl -o processwire-master.zip https://codeload.github.com/processwire/processwire/zip/master`) and that also seemed to work!
