### ISSUE TITLE
--dbPass should accept empty password

### ISSUE THREAD

**Issue by uiii** [wireshell/wireshell#54]
Hi, in my MySQL setup I have no password set for a user. But when I pass `--dbPass ""` it will still prompt for a password. If I just press enter and leave the password installation continue without problems. The problem is I want to use wireshell in a script without user interaction, so the password prompt is a trouble.

**Comment by uiii** [comment]
As the easy solution I see to ask for password only when no `--dbPass` options is passed, but not when the empty password is passed.

**Comment by justb3a** [comment]
hi, I cannot find a possibility to determine whether an empty option has been passed or not.
`$this->input` contains the passed options array **but** this property is protected and I cannot access that protected property. All available methods check for a value or merge the options with the defaults:

```
/Symfony/Component/Console/Input/ArgvInput

getOptions()
Returns all the given options merged with the default values.

hasOption(string $name)
Returns true if an InputOption object exists by name. 

hasParameterOption(string|array $values)
Returns true if the raw parameters (not parsed) contain a value.

getParameterOption(string|array $values, mixed $default = false)
Returns the value of a raw option (not parsed).

getOption(string $name)
Returns the option value for a given option name.
```

**Comment by uiii** [comment]
Hi, yes it looks like there is no suitable method for it. I made a little test and find out `getOption` returns `NULL` if the option is not present. Thus when the `--dbPass` option requires a value the empty password must be specified as an empty string. So you can just check if the password value is `NULL`.

**Comment by justb3a** [comment]
I checked both cases and both returned `Null`, there wasn't any difference.

```
wireshell new foo --dbPass=""
wireshell new foo

var_dump($this->input->getOption('dbPass');
NULL
```

**Comment by uiii** [comment]
Really, I don't understand. It must behave differently for me. I'm on Windows, PHP 5.6.

**Comment by uiii** [comment]
I've just changed the line https://github.com/wireshell/wireshell/blob/master/src/Commands/Common/NewCommand.php#L167 to `if (is_null($dbPass))` and it works as I need.

**Comment by justb3a** [comment]
At the moment I'm not able to submit an empty string:

```
wireshell new foo --dbPass=""

[Symfony\Component\Console\Exception\RuntimeException]
The "--dbPass" option requires a value.
```

Therefore I changed the input option from required to optional:

```
-  ->addOption('dbPass', null, InputOption::VALUE_REQUIRED, 'Database password')
+  ->addOption('dbPass', null, InputOption::VALUE_OPTIONAL, 'Database password')
```

```
var_dump($input->getOption('dbPass'));
var_dump(is_null($input->getOption('dbPass')));
```

```
❯ wireshell new _foo --dbPass=""

NULL
bool(true)

❯ wireshell new _foo

NULL
bool(true)
```

I'm on Mac, PHP7, develop branch.

**Comment by uiii** [comment]
Ah I found the reason why you are getting another results. The parameter parsing behaves differently when you use `--dbPass ""` and `--dbPass=""`. The first case is the one I've used. The second case is yours and will throw the exception as you mentioned. This looks like a bug in the Symfony's library.

**Comment by justb3a** [comment]
Nope.

InputOption::VALUE_OPTIONAL
```
❯ wireshell new foo --dbPass ""

NULL
bool(true)
```

InputOption::VALUE_REQUIRED
```
❯ wireshell new _foo --dbPass ""

[Symfony\Component\Console\Exception\RuntimeException]
The "--dbPass" option requires a value.
```

**Comment by uiii** [comment]
Which version of `symfony/console` do you have installed?

**Comment by justb3a** [comment]
^^

**Comment by uiii** [comment]
Maybe found the solution: https://github.com/symfony/symfony/issues/11572#issuecomment-197929086

`$input->hasParameterOption('--dbPass'));`

**Comment by justb3a** [comment]
That's strange. I'm quite sure, I tested this yesterday. But now it seems to work!

```
❯ wireshell new foo --dbPass=""
bool(true)

❯ wireshell new _foo

bool(false)
```

**Comment by uiii** [comment]
I've tried it before as well, but I tried it this way: `$input->hasParameterOption('dbPass')` without `--`, but this don't work.

**Comment by uiii** [comment]
Will you update it? Or shall I make an PR?

**Comment by justb3a** [comment]
I'll update it, but I'll add it to the develop branch. So it will be released with the next version.

**Comment by uiii** [comment]
OK fine 👍 . Will you update 0.6.0 version too, or will the new version support PW 2.x?

**Comment by justb3a** [comment]
[Added.](https://github.com/wireshell/wireshell/commit/2f623130ad3cd7d6ebb7b9e3a03a3bbf0c4d6106)

Unfortunately there won't be any 2.x support.

**Comment by uiii** [comment]
But could you make a hotfix for 0.6.0?

**Comment by justb3a** [comment]
Actually I won't support older versions. Sorry.

**Comment by uiii** [comment]
OK, never mind. I made a patch myself.
