### ISSUE TITLE
--adminUrl param doesn't work [develop branch]

### ISSUE THREAD

**Issue by uiii** [wireshell/wireshell#56]
Hi, I've found out the `--adminUrl` param doesn't work in develop branch. You would surely find it soon.

Problem is there [src/Commands/Common/NewCommand.php#L155-L156](https://github.com/wireshell/wireshell/blob/1f1f7cfdcf3bd4969a1e8a8cded9a093393de545/src/Commands/Common/NewCommand.php#L155-L156), as you are using `admin_name` in defaults.

**Comment by justb3a** [comment]
`--adminUrl` is the right one. Thanks for submitting. I've fixed it.
