### ISSUE TITLE
Parse Error in Wireshell

### ISSUE THREAD

**Issue by StanLindsey** [wireshell/wireshell#60]
When running `wireshell` on the command line we get the following error:

`Parse error: parse error in /Users/Stan/.composer/vendor/wireshell/wireshell/src/Helpers/PwUserTools.php on line 23`

The Line is this:
`public function init(OutputInterface $output, InputInterface $input) {
    parent::setOutput($output)::setInput($input)::bootstrapProcessWire();
  }`

Php version is 5.6.28.

**Comment by marcus-herrmann** [comment]
Which ProcessWire/wireshell version do you use?

**Comment by justb3a** [comment]
PHP version issue :/

**Comment by justb3a** [comment]
All occurrences have been replaced, I just released a new version (1.0.2). Should be working now.
