### ISSUE TITLE
profile import failure

### ISSUE THREAD

**Issue by Stikki** [wireshell/wireshell#62]
Howdy

file: \Commands\Common\NewCommand.php

import was missing:

`use Distill\Distill;`

extract structure was wrong, so changed from Lines 561-562:

`$extractPath = $this->projectDir . DIRECTORY_SEPARATOR . '.' . uniqid(time()) . DIRECTORY_SEPARATOR . 'pwprofile';
      $extractionSucceeded = $distill->extractWithoutRootDirectory($profile, $extractPath);`

to

`$extractPath = sys_get_temp_dir().DIRECTORY_SEPARATOR.uniqid(time()).DIRECTORY_SEPARATOR;
      $extractionSucceeded = $distill->extract($profile, $extractPath);`

**Comment by netcarver** [comment]
@Stikki Thanks for reporting the fix - I just hit this issue too.

**Comment by justb3a** [comment]
Thanks for reporting, I have corrected it now.
