### ISSUE TITLE
Error running wireshell new twice in the same folder

### ISSUE THREAD

**Issue by ivangretsky** [wireshell/wireshell#67]
Good day!

When I run a `wireshell new` command in a newly created folder for the 1st time, I am able to install PW. But if I remove all the files from the folder and run `wireshell new` again, I get an error:

```
Preparing project...

  [RuntimeException]
  ProcessWire can't be installed because the downloaded package is corrupted
  or because the installer doesn't have enough permissions to uncompress and
  rename the package contents.
  To solve this issue, check the permissions of the /mnt/d/xampp/htdocs directory and
  try installing ProcessWire again.
  new
```

It seems like permissions got changed somehow. I am on Windows 10 running wireshell in WSL. I check the permissions of the folder in WSL and in Windows- they seem to be ok. But I even can't delete the folder in windows. It saus something like "Can't delete. The folder is opened elsewhere".

Is it only WSL problem? Can you suggest any fix?

**Comment by justb3a** [comment]
hi,
please make sure to refresh the current working directory after installing ProcessWire using the new command / after removing the files. Just type `cd .` or ``cd `pwd` `` (the long way: by `cd ..` and `cd {dirname}` move up and back into the directory). 
I hope this fixes your issue.
